# Generated by Django 4.2 on 2023-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0003_alter_cardetail_accident_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
